input {
  file {
    path => "/app/logs/spring-boot-app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} \\[%{DATA:thread}\\] %{LOGLEVEL:level}\\s+%{DATA:logger} - %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss,SSS"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-app-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
